version : "2.2"
services:
  project_pin_api:
    image : verc112/pinterest_api
    restart : always
    volumes :
      - ./project_pin_API.py:/Pinterest_App/API/project_pin_API.py
    ports:
      - "5002:80"
    networks:
      - pin_api

  project_user_emulation:
    image: verc112/pinterest_user_emulation
    restart : always
    ports:
    - "5005:80"
    depends_on:
      - project_pin_api  
    networks:
      - pin_api

networks:
  pin_api:
      name: pin_api